### ISSUE TITLE
3팀 : docker-compose.yml 파일입니다.

### ISSUE THREAD

**Issue by pdh4869** [beyond-sw-camp/beyond-sw-camp-be01_4nd_mini-project#17]
```
version: '3.8'

services:
  mariadb-db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: maria
      MYSQL_DATABASE: todo_db

  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mariadb-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb-db:3306/todo_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: maria
```

**Comment by pdh4869** [comment]
# dockerfile
```
version: '3.8'

services:
  mariadb-db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: maria
      MYSQL_DATABASE: todo_db

  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mariadb-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb-db:3306/todo_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: maria
```
